# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Michelle Vick
title: Programmer
email: michelle.l.vick@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: facespics
github_username:  milivi
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: michelle-vick
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  As a recent computer science graduate I am curious and motivated to improve my skills and contribute to a team. I am currently a programmer at Cutco Corporation. I am passionate about clean, readable, maintainable code.

  I am most skilled in: <mark>Python</mark> and <mark>Java</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Outside of the digital world, I may be found reading or kayaking.
#- [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
